### ISSUE TITLE
deepstack_object_camera entity not available

### ISSUE THREAD

**Issue by aceonce** [robmarkcole/HASS-Deepstack-object#267]
The entity for deepstack_object_camera status shows as read only and not available, hence there's no object detected by deepstack. I can manually trigger via HA developer tool and images would be processed. Any ideas where the problem might be?

![image](https://user-images.githubusercontent.com/77632305/152280047-7ab84e2c-1444-40ed-b519-e573b5ff5846.png)

**Comment by Dysannl** [comment]
i'm also seeing these issues, 
but further investigation shows this in the HASS startup log:

```
Logger: homeassistant.components.image_processing

Source: custom_components/deepstack_object/image_processing.py:274
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deepstack_object/image_processing.py", line 222, in setup_platform
    object_entity = ObjectClassifyEntity(
  File "/config/custom_components/deepstack_object/image_processing.py", line 274, in __init__
    self._dsobject = ds.DeepstackObject(
TypeError: __init__() got an unexpected keyword argument 'ip'

````

**Comment by robmarkcole** [comment]
@DRazumovskiy this is correct, thanks
