### ISSUE TITLE
KeyError: 'predictions'

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-Deepstack-object#40]
I see the error below when there is a problem with the camera:
```
Traceback (most recent call last):
  File "/Users/robincole/Documents/GitHub/home-assistant/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/Users/robincole/Documents/GitHub/home-assistant/homeassistant/helpers/entity.py", line 378, in async_device_update
    await self.async_update()
  File "/Users/robincole/Documents/GitHub/home-assistant/homeassistant/components/image_processing/__init__.py", line 132, in async_update
    await self.async_process_image(image.content)
  File "/Users/robincole/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/robincole/.homeassistant/custom_components/deepstack_object/image_processing.py", line 157, in process_image
    predictions_json = response.json()["predictions"]
KeyError: 'predictions'
```

**Comment by robmarkcole** [comment]
OK it is not a bad image which causes this issue, a bad image returns:
```
{'success': True, 'predictions': []}
```

**Comment by robmarkcole** [comment]
Am now catching zero predictions
