### ISSUE TITLE
OSError: cannot identify image file

### ISSUE THREAD

**Issue by JohnLahr** [robmarkcole/HASS-Deepstack-object#95]
Running both Home Assistant and DeepStack in separate Docker containers, I get the following error when calling `image_processing.scan` on entity ID `image_processing.deepstack_person_detector`:

```
Update for image_processing.deepstack_person_detector fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 281, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 135, in async_update
    await self.async_process_image(image.content)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deepstack_object/image_processing.py", line 161, in process_image
    io.BytesIO(bytearray(image))
  File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7f43202fca10>
```

My DeepStack image processor config:

```
---
# DeepStack
# https://github.com/robmarkcole/HASS-Deepstack-object
platform: deepstack_object
ip_address: deepstack
port: 5000
api_key: !secret deepstack_api_key
source:
  - entity_id: camera.uvc_g4_pro_7884
    name: deepstack_person_detector
```

And my camera config:

```
# Generic IP Camera
# https://www.home-assistant.io/integrations/generic_ip_camera
platform: generic
name: uvc_g4_pro_7884
stream_source: "rtsp://[redacted]"
still_image_url: [redacted]
```
I've confirmed that the Home Assistant container can resolve and reach the DeepStack container using its service discovery DNS (`deepstack`), and I can `curl` the URL and port successfully. I get this error both with and without configured a `save_file_folder` option.

**Comment by robmarkcole** [comment]
Could be that the image is malformed or corrupted. Is the camera feed displaying correctly on the HA front-end?

**Comment by JohnLahr** [comment]
I don't think it's corrupted; it displays fine on the front end. I have a picture entity card using that feed.

**Comment by robmarkcole** [comment]
It might be occuring only intermittently

**Comment by robmarkcole** [comment]
stale
